### ISSUE TITLE
Fixing alignment issue with long usernames

### ISSUE THREAD

**Issue by gabrysia694** [gabrysia694/Gym-Junkies#103] opened 2023-04-30 20:53 UTC
Longer `gh-name` gets misaligned on a exercise card. It'd look better centered 

<img width="917" alt="xx" src="https://user-images.githubusercontent.com/97764356/235375678-9646a7bb-3048-45e7-9511-a4facb771912.png">

**Comment by rprav-n** [comment] 2023-05-01 08:23
Hi @gabrysia694 

Can I work on this?

**Comment by gabrysia694** [comment] 2023-05-01 08:40
Hi @rprav-n, of course! I’ll assign you to it right away

**Comment by rprav-n** [comment] 2023-05-01 17:56
Hi @gabrysia694 

It seems that the issue was caused by the text color of the phrase "Added by" being set to white in dark mode, which resulted in misalignment.

And do we still need the alignment to be centred?

Here's the screenshot:

![image](https://user-images.githubusercontent.com/46050644/235500536-27e6390f-9f33-49e2-84a1-7ee483810338.png)

**Comment by gabrysia694** [comment] 2023-05-01 19:41
> Hi @gabrysia694
> 
> It seems that the issue was caused by the text color of the phrase "Added by" being set to white in dark mode, which resulted in misalignment.
> 
> And do we still need the alignment to be centred?
> 
> Here's the screenshot:
> 
> ![image](https://user-images.githubusercontent.com/46050644/235500536-27e6390f-9f33-49e2-84a1-7ee483810338.png)

you're right, my bad! then fixing "Added by" color in dark mode should fix the issue, no need to center the alignment

**Comment by Ankit5kumar** [comment] 2023-05-02 06:18
Are the above changes fixed?

**Comment by rprav-n** [comment] 2023-05-02 16:49
@gabrysia694 Issue has been fixed in this PR: https://github.com/gabrysia694/Gym-Junkies/pull/110

@Ankit5kumar Yes, it's fixed

**Closed as completed** 2023-05-02 16:55 UTC
Labels: good first issue, Eddiehub:good-first-issue
